# https://github.com/DavidAnson/markdownlint#rules--aliases

# MD004 ul-style - Unordered list style
MD004:
  style: "consistent"

# MD005 list-indent - Inconsistent indentation for list items at the same level
MD005: true

# MD007 ul-indent - Unordered list indentation
MD007:
  indent: 4
  start_indented: false

# MD013 line-length - Line length
MD013: false

# MD033 no-inline-html - Inline HTML
MD033: false

# MD041 first-line-heading/first-line-h1
MD041: false

# MD046 code-block-style Code block style
MD046: false
